seed: 44

# How to drive the main simulation?
simulation:
  # dynamics model to use: dynamics_2d_linear | dynamics_3d_linear | dynamics_3d
  dynamics_model: dynamics_3d_linear
  # cave to explore: chamber | tunnels | grapevine
  cave: grapevine
  agents:
    num_agents: 2
    # policy to use: policy_random | policy_mppi
    policy: policy_mppi
  render:
    # If true, produce an image for every step of the simulation
    # and render it in a window, then compile into a video at the end.
    # This slows down the simulation.
    enabled: true
    # Making this < 1 will speed up rendering at the cost of 
    # quality/layout niceness
    figure_size_multiplier: 1.0
  # How many waypoints to task each agent with reaching?
  num_waypoints: 8
  # You can also provide your own waypoints manually, but they 
  # must be per agent, and they need to be with reference
  # to a cave's graph coordinate system, not world coordinates.
  graph_waypoints_provided: true 
  # This file relates the graph waypoints to world coordinates.
  graph_waypoints_file: "src/prospector/caves/example_graphs/chamber/3d/15/graph.npz"
  #graph_waypoints_file: "src/prospector/caves/example_graphs/tunnels/3d/15/graph.npz"
  # From the paper, we provide these example waypoints:
  graph_waypoints:
    [
      # Agent 1
      [0, 5, 10, 4, 1, 3, 6, 13, 14, 13, 6, 5],
      # Agent 2
      [0, 11, 7, 11, 0, 12, 8, 12, 2, 9, 1, 0]
    ]
  # graph_waypoints:
  #   [
  #     # Agent 1
  #     [0, 9, 13, 9, 0, 2, 6, 5, 7, 8 ,7, 5, 6, 2]
  #     # Agent 2
  #     [0, 1, 10, 11, 10, 3, 4, 12, 4, 14, 5, 6, 2, 0]
  #   ]

  # After reaching all waypoints, how many steps to continue simulating
  num_steps_to_simulate_after_completion: 50

# ----------------------------------------------------------------
# Relating to the loading, processing, and plotting of the cave data
# ----------------------------------------------------------------
caves:

  chamber:
    source: DARPA SubT Challenge Final Event
    metadata: 
     - key: DARPA SubT Section Number
       value: 5
    relative_path: "/src/assets/chamber.ply"
    known_internal_xyz: [59.301, 105.96, 0.136567]
    slice_for_2d:
      z: -3.1
      thickness: 0.1
    voxel_size: 0.1
    plotting:
      obstacle_points:
        max_num: 20000
        alpha: 0.1

  tunnels:
    source: DARPA SubT Challenge Final Event
    metadata: 
      - key: DARPA SubT Section Number
        value: 6
    relative_path: "/src/assets/tunnels.ply"
    known_internal_xyz: [29.1537, 39.3087, -2.45432]
    slice_for_2d:
      z: -2.25432
      thickness: 0.1
    voxel_size: 0.1
    plotting:
      obstacle_points:
        max_num: 10000
        alpha: 0.1

  grapevine:
    source: Stanford Expedition
    metadata: 
      - key: Expedition date
        value: 24 May 2025
      - key: Survey team
        value:
          - Isaac R. Ward
          - Michelle Ho
          - Maximilian Adang
    relative_path: "/src/assets/grapevine.ply"
    known_internal_xyz: [-0.672833, 0.089741, 1.85611]
    slice_for_2d:
      z: 1.94226
      thickness: 0.01
    voxel_size: 0.2
    plotting:
      obstacle_points:
        max_num: 20000
        alpha: 0.1

# ----------------------------------------------------------------
# Relating to rewards
# ----------------------------------------------------------------
rewards:

  waypoint_following:
    distance_weight: 1.0
    control_effort_weight: 0.1
    collision_penalty: 1e6
    # If this is higher, then the agent can be within this number
    # * their agent_radius of the goal to consider it reached
    multiplier_within_radius_of_goal: 3.0

# ----------------------------------------------------------------
# Relating to policies
# ----------------------------------------------------------------
policies:

  policy_mppi:
    num_samples: 32
    horizon: 10
    lambda_: 1.0
    noise_std: 0.05
    sampling_mode: "uniform"  # uniform | gaussian

# ----------------------------------------------------------------
# Relating to agents
# ----------------------------------------------------------------
agents:

  agent_radius: 0.1
  history_length: 16

# ----------------------------------------------------------------
# Relating to the environment / simulation settings
# ----------------------------------------------------------------
environment:

  max_episode_length: 1000

# ----------------------------------------------------------------
# Relating to the underlying physical dynamics models
# ----------------------------------------------------------------
dynamics:

  dynamics_2d_linear:
    dt: 0.25
    # State is [x, y]
    state_dim: 2
    state_limits:
      - [null, null]
      - [null, null]
    # Action is [ux, uy]
    action_dim: 2
    action_limits:
      - [-2, 2]
      - [-2, 2]  
    position_dimensions: [0, 1]

  dynamics_3d_linear:
    dt: 0.25
    # State is [x, y, z]
    state_dim: 3
    state_limits:
      - [null, null]
      - [null, null]
      - [null, null]
    # Action is [ux, uy, uz]
    action_dim: 3
    action_limits:
      - [-2, 2]
      - [-2, 2]
      - [-2, 2]
    position_dimensions: [0, 1, 2]

  dynamics_3d:
    dt: 0.1
    # State is
    # [x, y, z, 
    # vx, vy, vz, 
    # roll, pitch, yaw, 
    # p, q, r]
    state_dim: 12
    state_limits:
      - [null, null]
      - [null, null]
      - [null, null]
      - [null, null]
      - [null, null]
      - [null, null]
      - [null, null]
      - [null, null]
    # Action is [w_rotor_1, w_rotor_2, w_rotor_3, w_rotor_4]
    action_dim: 4
    action_limits:
      - [-0.5, 0.5]
      - [-0.5, 0.5]
      - [-0.5, 0.5]
      - [-0.5, 0.5]
    position_dimensions: [0, 1, 2]